import Head from "next/head";
import { Fragment } from "react";

function Layout(props) {
  return (
    <Fragment>
      <Head>
        <meta charSet="utf-8" />
        <title>Layout Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {props.children}
      </main>
    </Fragment>
  );
}

export default Layout;
